-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  --
-- Decoration Settings
--
-- 由 UserConfigs/UserDecorations.conf 转换为 lua (Hyprland >= 0.55)
-- general { ... } / decoration { ... } / group { ... } -> hl.config({ ... })

-- Hyprland Wiki Links
-- Animation - https://wiki.hyprland.org/Configuring/Animations/
-- Decoration - https://wiki.hyprland.org/Configuring/Variables/#decoration

-- Sourcing colors generated by matugen
-- [ii 迁移] 原 wallust 方案已废弃。colors.lua 由 matugen 从当前壁纸生成，
-- 内部已调用 hl.config 设置 general.col（边框色）与 misc.background_color，
-- 并额外导出 themePrimary / themeOutline 等全局变量供本文件使用。
-- 这些变量由 ~/.config/theme-switcher/ 的主题切换器统一管理
-- （可切到 gruvbox 等静态主题，colors.lua 会被换成同样导出 theme* 的版本）。
require("colors")

hl.config({
    general = {
        border_size = 2,
        gaps_in = 2,
        gaps_out = 4,
        -- col 由 colors.lua 设置，此处不再重复定义以免覆盖
    },
})

hl.config({
    decoration = {
        rounding = 10,

        active_opacity = 1.0,
        inactive_opacity = 0.9,
        fullscreen_opacity = 1.0,

        dim_inactive = true,
        dim_strength = 0.1,
        dim_special = 0.8,

        shadow = {
            enabled = true,
            range = 3,
            render_power = 1,

            -- [ii 迁移] 原 color12/color10 由 wallust 提供，现改用主题切换器导出的变量
            color = themePrimary,
            color_inactive = themeOutline,
        },

        blur = {
            enabled = true,
            size = 6,
            passes = 2,
            ignore_opacity = true,
            new_optimizations = true,
            special = true,
            popups = true,
        },
    },
})

hl.config({
    group = {
        col = {
            border_active = color15,
        },

        groupbar = {
            col = {
                active = color0,
            },
        },
    },
})
