-- Generated by nwg-displays on 2026-05-18 at 00:48:06. Do not edit manually.
--
-- 由 monitors.conf 转换为 lua (Hyprland >= 0.55)
-- monitor=OUTPUT,MODE,POSITION,SCALE -> hl.monitor({ output=..., mode=..., position=..., scale=... })

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080@180",
    position = "0x0",
    scale    = 1,
})

hl.monitor({
    output   = "eDP-1",
    mode     = "2560x1440@240.0",
    position = "-1600x0",
    scale    = 1.6,
})
