distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 5.1.16
install_time: "Sat Aug 23 02:20:52 2025"
installation_id: "6085fa0c-f6d7-402f-a489-b3e45aa9dec4"
rime_version: 1.17.0
update_time: "Fri Sep 11 00:37:48 2026"